### PR TITLE
Add command for validating package collections

### PR DESCRIPTION
**Pull request by yim-lee**
Use `JSONPackageCollectionModel.V1.Validator` provided in SwiftPM to validate package collections and print warnings/errors accordingly.

### CODE REVIEW

**Review by tomerd — APPROVED** [review]
nice!

**Comment by yim-lee** [comment]
@swift-ci test

**Comment by yim-lee** [comment]
@swift-ci test

**Comment by yim-lee** [comment]
@swift-ci test

**Comment by yim-lee** [comment]
@swift-ci test

**Comment by yim-lee** [comment]
@swift-ci test

**Comment by yim-lee** [comment]
@swift-ci test

**Comment by yim-lee** [comment]
@swift-ci test

**Comment by yim-lee** [comment]
@swift-ci test

**Comment by yim-lee** [comment]
Docker builds pass locally. Merging.

**Pull request merged**
