### PR TITLE
[Don't Merge] Update README.md

### PR DESCRIPTION
**Pull request by shahmishal**

### CODE REVIEW

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by yim-lee** [comment]
Swift 5.2 failure known. https://github.com/apple/swift-package-manager/pull/3097 addresses it.

**Comment by shahmishal** [comment]
@swift-ci test

**Pull request closed without merging**
